<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Return to CATS</name>
   <tag></tag>
   <elementGuidId>8291a208-a807-4170-8879-c6660dbe36f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id='BackLink'] a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BackLink']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1aff16e1-43c9-4386-a271-bafaee7a5901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/actions/Catalog.action?viewCategory=&amp;categoryId=CATS</value>
      <webElementGuid>923017b6-6a4c-481b-89bf-069cfd5b69d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Return to CATS</value>
      <webElementGuid>dfd1761d-7659-41f7-bb1f-03a4d7d4737a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BackLink&quot;)/a[1]</value>
      <webElementGuid>55528158-870c-4870-883f-63944aa2d1b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BackLink']/a</value>
      <webElementGuid>b0ce2ed9-3a2f-4330-88f2-c1dc0aa4cbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Return to CATS')]</value>
      <webElementGuid>f2067695-ecbd-41d0-a661-5721c96d9c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/following::a[6]</value>
      <webElementGuid>abf70072-2d59-4e54-81e4-58e2c0ba4fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/following::a[7]</value>
      <webElementGuid>4c436b1f-4f2b-4863-9d4e-0800273c60c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manx'])[1]/preceding::a[1]</value>
      <webElementGuid>0ace477d-90a4-4985-ab23-7e253232794e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item ID'])[1]/preceding::a[1]</value>
      <webElementGuid>97a83085-eb03-47a2-b04f-12605c8d0140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Return to CATS']/parent::*</value>
      <webElementGuid>518b5f12-1305-47f3-ae43-de690f21d984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/actions/Catalog.action?viewCategory=&amp;categoryId=CATS')])[2]</value>
      <webElementGuid>a8e23063-6716-4df1-a844-cabe4431448f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>4fa5c353-40eb-48c5-8a79-16f7e83cc0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/actions/Catalog.action?viewCategory=&amp;categoryId=CATS' and (text() = 'Return to CATS' or . = 'Return to CATS')]</value>
      <webElementGuid>e47d2adb-d7c5-418b-a2b2-db7e6827154d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
