<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Return to FL-DSH-01</name>
   <tag></tag>
   <elementGuidId>e8bd7699-e8e9-4dec-b72f-cc94679e26bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BackLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BackLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>96766cb0-6bc9-4b9e-8353-e377c00ef805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BackLink</value>
      <webElementGuid>0bc067c3-c9dc-401d-adad-8d544d1a4c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Return to FL-DSH-01</value>
      <webElementGuid>ceb29396-c286-4dc4-88f8-9526eeaf903e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BackLink&quot;)</value>
      <webElementGuid>2c5edc89-0c51-4045-97c5-373f6475d19b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='BackLink']</value>
      <webElementGuid>a4c64bdf-8ca8-4ef7-9219-6601b64139c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Content']/div</value>
      <webElementGuid>cc0c642d-2cda-4edb-a8ea-514c5cb6389f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/following::div[6]</value>
      <webElementGuid>f1bff81b-5557-4955-9be5-de16843e4387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/following::div[6]</value>
      <webElementGuid>04c8b171-84c5-4514-9323-c04da7237ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Great for reducing mouse populations'])[1]/preceding::div[1]</value>
      <webElementGuid>711043f2-ab01-41d4-81b3-d0b5c1bfb458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>4aa7c6b7-2a33-4d6c-a6e6-211c0da501cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'BackLink' and (text() = 'Return to FL-DSH-01' or . = 'Return to FL-DSH-01')]</value>
      <webElementGuid>4e3567c3-cf09-4cd6-ae46-f7d51ac4559b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
