<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Return to FL-DLH-02</name>
   <tag></tag>
   <elementGuidId>4554065f-385e-43d6-845b-b8aff3b2b2dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BackLink > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BackLink']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e4c720ae-6e4c-4cfe-bd2a-4d4556513068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/actions/Catalog.action?viewProduct=&amp;productId=FL-DLH-02</value>
      <webElementGuid>638cad8b-5825-453c-8f46-5b88f1646329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Return to FL-DLH-02</value>
      <webElementGuid>667a9e07-ce45-4cd4-9219-817fa011305d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BackLink&quot;)/a[1]</value>
      <webElementGuid>5a5f8635-3cc7-43fa-8c6c-34a50799cc1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BackLink']/a</value>
      <webElementGuid>e4e366e9-5db3-43fe-9faf-c2726e8daf85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Return to FL-DLH-02')]</value>
      <webElementGuid>e7f5549d-5275-4649-b8b8-34c1a1c5ac8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/following::a[6]</value>
      <webElementGuid>f4a1a200-1efd-4cdb-8e7c-083ac41d5299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/following::a[7]</value>
      <webElementGuid>ade38c55-7563-483d-9fb0-c1e48ab660a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Friendly house cat, doubles as a princess'])[1]/preceding::a[1]</value>
      <webElementGuid>f7cf5da7-d0b3-43bf-a04d-25b5c37d9438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EST-16'])[1]/preceding::a[1]</value>
      <webElementGuid>a1005065-7264-4a27-8146-cdab793400d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Return to FL-DLH-02']/parent::*</value>
      <webElementGuid>7d457ee6-8147-4c26-b107-059cfe687616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/actions/Catalog.action?viewProduct=&amp;productId=FL-DLH-02')]</value>
      <webElementGuid>538345b8-f5c2-485b-8d7c-17a93551fff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>a4b69569-5369-40e3-943d-92e882b782c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/actions/Catalog.action?viewProduct=&amp;productId=FL-DLH-02' and (text() = 'Return to FL-DLH-02' or . = 'Return to FL-DLH-02')]</value>
      <webElementGuid>e4a2915a-ad31-42be-a4eb-5100e781e970</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
